name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript compilation check
        run: npx tsc --noEmit

      - name: Code formatting check
        run: npx prettier --check "src/**/*.{ts,js,json}"

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test || echo "No tests configured yet"

      - name: Security audit
        run: npm audit --audit-level moderate

      - name: Test CLI installation
        run: |
          npm pack
          npm install -g firebase-tools-cli-*.tgz
          firebase-tools-cli --help

      - name: All checks passed
        run: echo "✅ All CI checks passed successfully!"
