name: Code Quality

on:
  push:
    branches: [development]
  pull_request:
    branches: [main, development]

permissions:
  contents: read

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript compilation
        run: npx tsc --noEmit

      - name: Run Prettier check
        run: npx prettier --check "src/**/*.{ts,js,json}"

      - name: Build verification
        run: npm run build

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Check for unused dependencies
        run: |
          # This will help identify unused dependencies
          npx depcheck --ignores="@types/*,prettier,typescript,esbuild" || echo "Consider reviewing unused dependencies"
